version: '3.7'
services:
  mongodb_container:
    container_name: mongo
    image: mongo:latest
    networks:
      - easycargo_api_queries
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks:
  easycargo_api_queries:
    name: easycargo_api_queries